//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liquid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messsage
    {
        public int MessageID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SendID { get; set; }
        public string MessageInfo { get; set; }
        public Nullable<System.DateTime> MessgaeTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
